# Generated by the vetiver package; edit with care
cat("Current directory", getwd(), "\n")
library(pins)
library(plumber)
library(rapidoc)
library(vetiver)

# Packages needed to generate model predictions
if (FALSE) {
  library(parsnip)
  library(recipes)
  library(stats)
  library(workflows)
}
pin_loc <- pins:::github_raw("JamesHWade/r-mlops/main/pins-r/_pins.yaml")
b <- board_url(pin_loc)
v <- vetiver_pin_read(b, "penguins_model")

#* @plumber
function(pr) {
  pr %>% vetiver_api(v)
}